<a href="https://colab.research.google.com/github/LochanaBandara03/ML_tutorial/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  numpy as np
print(np.__version__)

1.26.4


In [ ]:
#1 -dimensional array - Vector
a1 = np.array([1, 2, 3])

#2-dimensional array - marix
a2 = np.array([[1, 2, 3 ],
               [4, 5, 6 ]])

#3-dimensional array - matrix
a3 = np.array([[[1, 2, 3 ],
                [4, 5, 6 ]],

               [[7, 8, 9 ],
                [10, 11, 12]]])

a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

In [ ]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

##Pandas Dataframe out of NumPy arrays

In [ ]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5,3)),   #Random integer
                  columns=['a', 'b', 'c'])
df

a  b  c
0  3  8  9
1  3  8  7
2  5  7  6
3  2  8  7
4  5  4  3

In [ ]:
df2 = pd.DataFrame(a2)
df2

0  1  2
0  1  2  3
1  4  5  6

##Creating arrays

In [ ]:
#Create a simple array
simple_array = np.array([1, 2, 3 ])
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

In [ ]:
#Create an array of ones
ones = np.ones([10, 2])
ones, ones.dtype

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 dtype('float64'))

In [ ]:
#Change the data type with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#Create an array of zeros
zeros = np.zeros([5, 3, 3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#Array within a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
#Random array
range_array = np.random.randint(10, size=(5,3))
range_array

array([[7, 0, 7],
       [0, 7, 4],
       [0, 7, 1],
       [9, 8, 9],
       [5, 9, 4]])

In [ ]:
#Random array of floats
np.random.random((5, 3))

array([[0.85513804, 0.20330541, 0.42453177],
       [0.78218562, 0.87306403, 0.99937227],
       [0.43997962, 0.00979777, 0.86635432],
       [0.26138656, 0.02222441, 0.0359935 ],
       [0.84567526, 0.2191843 , 0.50709122]])

In [ ]:
np.random.rand(5, 3)

array([[0.97609589, 0.99303614, 0.38081299],
       [0.97911001, 0.15013216, 0.34243817],
       [0.99488529, 0.1291304 , 0.32966169],
       [0.08559278, 0.16990469, 0.90314283],
       [0.08652257, 0.55201079, 0.14494333]])